"""Authored fiction informed by public industry context, never claims about real staff."""
SCENARIOS = [
    {'id': 'alderbank', 'name': 'Alderbank | Finance',
     'background': 'Fictional regional bank after three acquisitions. Branches retain their old identities. A recent customer incident was known by branch staff before headquarters. Meeting purpose: detect customer impact earlier and prove recovery before the next integration milestone. Speed, operational sustainability and credible evidence all matter.',
     'source': 'https://www.sec.gov/Archives/edgar/data/1281761/000128176126000019/rf-20251231.htm',
     'people': [
         ('Morgan Hale', 'Infrastructure architect', 'Networking, recovery, integration', 'Calm, curious, dry humor', 'Make the next integration understandable to the engineer on call.', 'Veteran of an acquired bank and two conversions. Proud of an earlier design and slow to let it go. Restores radios; casual baseball fan. Trust grows when someone acknowledges what already works.'),
         ('Riley Chen', 'Operations lead', 'Incidents, handovers, maintenance', 'Practical, candid, protective of the team', 'Stop being the person every incident depends on.', 'Meticulous handovers but still hoards critical tasks. Enjoys cooperative board games and dislikes one player taking over. Respects Casey but worries about promises without support.'),
         ('Casey Patel', 'Digital engineering leader', 'Customer journeys, delivery, integration', 'Energetic, direct, willing to change their mind', 'Let customers finish routine tasks without calling a branch.', 'Came from consumer software for more meaningful work. Sometimes underestimates bank integration. Runs a film club. Thinks operations says no too early.'),
         ('Evelyn Brooks', 'Chief operating officer', 'Branch operations, customer service', 'Warm, concrete, impatient with abstract percentages', 'Make acquisitions improve the experience at the branch.', 'Started as a teller and still visits branches. An enthusiastic but unsuccessful gardener. Asks what a branch manager would notice first.'),
         ('Andre Lewis', 'Technology risk lead', 'Recovery evidence, controls', 'Careful, fair, open to small experiments', 'Make a recovery exercise prove that the business can operate.', 'Once signed off a technical recovery that did not restore useful service. Sings in a choir. Wants clear evidence, not ceremonial compliance.'),
         ('Tess Navarro', 'Branch director', 'Frontline communication, service continuity', 'Plainspoken, patient with people, impatient with acronyms', 'Give staff useful incident updates before customers ask.', 'Has lived through every acquisition. Restores furniture with her sister. Backs digital improvements but asks who supports the transition.') ]},
    {'id': 'calder', 'name': 'Calder Works | Manufacturing',
     'background': 'Fictional precision components maker with seven plants and two recent acquisitions. Older equipment and incompatible systems coexist with valuable undocumented workarounds. Culture: the machine does not care what the slides say. Meeting purpose: improve visibility and recovery at one pilot plant without disrupting production or adding unsupported work.',
     'source': 'https://www.sec.gov/Archives/edgar/data/76334/000007633425000035/ph-20250630.htm',
     'people': [
         ('Elena Marquez', 'Plant manager', 'Production, quality, staffing', 'Direct, observant, protective of operators', 'Make production predictable without burning people out.', 'Former quality engineer. Supports change when its owner stays through commissioning. Coaches youth softball. A pilot still costs real people time.'),
         ('Gabe Foster', 'Controls lead', 'Industrial controls, legacy equipment', 'Patient, skeptical of easy answers', 'Document enough knowledge to take an uninterrupted vacation.', 'Twenty years with mixed equipment. Proud of being useful but aware he is a bottleneck. Builds model boats. Asks what happens when the new system fails.'),
         ('Priya Nair', 'Enterprise platform architect', 'Integration, platform operations', 'Curious, specific, willing to revise a design', 'Make the next acquisition easier to integrate.', 'A prior standardization worked centrally but missed local needs. Earned Gabe\'s trust by working a night shift. Plays jazz piano.'),
         ('Marcus Bell', 'Finance director', 'Investment, operating costs, throughput', 'Friendly, skeptical of unearned savings', 'Reduce scrap and overtime with credible investment evidence.', 'A previous project promised savings that never arrived. Makes elaborate breakfasts. Will spend more if the operational tradeoff is clear.'),
         ('June Park', 'Quality systems lead', 'Traceability, inspection, records', 'Quiet until a missing detail matters', 'Connect production, inspection and shipment records reliably.', 'Lived through a difficult traceability investigation. Loves photography. Spots business requirements missed in infrastructure diagrams.'),
         ('Owen Price', 'Production planner', 'Scheduling, supply changes, customer commitments', 'Optimistic, fast talking, candid about workarounds', 'Avoid surprises and duplicate entry during schedule changes.', 'Keeps unofficial spreadsheets containing real exceptions the standard system misses. Plays pub trivia. Wants help, not a lecture about spreadsheets.') ]},
    {'id': 'prairie', 'name': 'Prairie Current Energy | Energy',
     'background': 'Fictional regional electric utility balancing renewable connections, aging assets and public service. Storm memories shape strong team loyalty. IT, operational technology and field crews have legitimate responsibility boundaries. Meeting purpose: improve operational visibility and recovery evidence while preserving control responsibility.',
     'source': 'https://www.sec.gov/Archives/edgar/data/86521/000103220826000010/sre-20251231.htm',
     'people': [
         ('Ruth Calder', 'Resilience director', 'Recovery planning, coordination', 'Calm, protective, skeptical of heroic assumptions', 'Make recovery work without one indispensable person.', 'Remembers exhausted staff after a storm more than the praise. Enjoys walking holidays. Rejects plans assuming everyone is rested and every dependency reachable.'),
         ('Samir Desai', 'Operational technology manager', 'Substations, control dependencies', 'Patient with honest questions, blunt about oversimplification', 'Gain visibility without adding unknown control dependencies.', 'Former substation engineer. Cooks for a large extended family. Can become an enthusiastic sponsor after trust is earned.'),
         ('Leah Ward', 'Dispatch systems supervisor', 'Dispatch information, abnormal operations', 'Plain language, detail oriented', 'Know which information to trust when systems disagree.', 'Came through shift work and remembers confusing screens. Reads mysteries. Focuses on decisions during abnormal conditions.'),
         ('Noah Bennett', 'Cloud integration lead', 'Integration, modern platforms', 'Enthusiastic, sometimes impatient', 'Modernize while retaining the knowledge of experienced staff.', 'Returned to the region from a software company. Plays amateur soccer. Debates Samir openly but seeks his design review privately.'),
         ('Denise Cole', 'Capital planning lead', 'Long term cost, staffing, maintenance', 'Careful with commitments, skeptical of false precision', 'Fund systems the organization can operate for five years.', 'Has seen ongoing costs sink promising projects. Volunteers in theater. Wants staffing and maintenance commitments before approving capital.'),
         ('Luis Ortega', 'Field services supervisor', 'Field work, connectivity, service records', 'Funny, practical, concrete', 'Reduce return trips caused by incomplete information.', 'Started as an apprentice. Repairs children\'s bikes. A seemingly minor connectivity assumption can change his whole assessment.') ]},
    {'id': 'meridian', 'name': 'Meridian Air | Transportation',
     'background': 'Fictional network airline informed by public United Airlines industry context, not a portrayal of United employees or internal systems. Multiple hubs, international routes and regional partners. Pride in safety and the next departure; disruption reveals information arriving at different speeds. Meeting purpose: prioritize failures by operational consequence and recover without creating another fragmented view.',
     'source': 'https://www.sec.gov/Archives/edgar/data/100517/000010051726000023/ual-20251231.htm',
     'people': [
         ('Maya Reed', 'Integrated operations director', 'Disruption coordination, operational decisions', 'Calm under pressure, impatient with bureaucracy', 'Establish a shared picture and clear ownership of the next action.', 'Came from airport operations and remembers difficult recoveries. Trail runner. Asks which decision becomes easier.'),
         ('Daniel Cho', 'Infrastructure reliability lead', 'Monitoring, service health, incidents', 'Generous mentor, candid, defensive when unfairly blamed', 'Show service health instead of thousands of unrelated alerts.', 'Built monitoring after an acquisition. Collects records. Wants ownership without a turf war and mentors junior engineers.'),
         ('Sofia Alvarez', 'Hub customer operations lead', 'Frontline communication, passenger service', 'Warm, quick wit, blunt about passenger impact', 'Give staff and passengers consistent disruption information.', 'Former gate supervisor. Enjoys dancing and family gatherings. Asks what the agent can tell the person at the desk.'),
         ('Ben Okafor', 'Digital journeys lead', 'Rebooking, customer communication', 'Imaginative, fast prototyping, curious', 'Help passengers resolve disruption without waiting in a queue.', 'Sometimes assumes dependencies are reliable. Makes short films. Sofia advocates for his work when frontline staff are involved early.'),
         ('Nina Shah', 'Technology portfolio director', 'Investment, integration, operating costs', 'Careful with promises, flexible about methods', 'Reduce duplicate investments with an honest account of value.', 'Integrated two organizations with overlapping platforms. Long distance cyclist. Asks which existing cost actually disappears.'),
         ('Cal Mercer', 'Maintenance systems duty manager', 'Maintenance records, handovers, availability', 'Reserved, precise, quietly funny', 'Keep records available and handovers unambiguous.', 'Former aircraft technician, slowly restores motorcycles. Defers decisions outside his authority and dislikes guesses disguised as facts.') ]},
]

for scenario in SCENARIOS:
    scenario['fiction_notice'] = 'All people, incidents and business details are authored fiction. The source provides industry context only.'
    scenario['cast'] = [dict(id=f"{scenario['id']}-{i}", name=p[0], role=p[1], expertise=p[2], style=p[3], objective=p[4], history=p[5]) for i, p in enumerate(scenario.pop('people'))]


def find_person(cast_id):
    return next((p for s in SCENARIOS for p in s['cast'] if p['id'] == cast_id), None)
