import {Operations} from './operations';
import React, {useEffect, useState} from 'react';

export async function api(path:string, body?:unknown) {
  const result=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
  if(!result.ok){const data=await result.json().catch(()=>null);throw new Error(typeof data?.detail==='string'?data.detail:'Request failed. Check the fields and try again.');}
  return result.json();
}
export function Access({role,onReady}:{role:'meeting'|'admin';onReady:()=>void}) {
  const [password,setPassword]=useState(''),[error,setError]=useState('');
  return <div className="app"><header><a href="/" className="brand">Audience / simulator</a><a href={role==='meeting'?'/?admin':'/'}>{role==='meeting'?'Admin':'Meetings'}</a></header><main className="login"><form className="config" onSubmit={async e=>{e.preventDefault();try{await api('/api/auth/'+role+'/login',{password});setPassword('');onReady();}catch(err){setError(String(err));}}}><p className="eyebrow">{role==='admin'?'ADMINISTRATION':'WELCOME'}</p><h1>{role==='admin'?'Admin sign in':'Join the practice room'}</h1><label>{role==='admin'?'Admin password':'Meeting password'}<input autoFocus type="password" autoComplete="current-password" required maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/></label><p className="error" role="alert">{error}</p><button className="primary">Sign in</button><p className="hint">Each meeting is private to its connection. Your shared password grants access, not an individual identity.</p></form></main></div>;
}
type Stats={today:string;paused:boolean;daily_by_stage:{stage:string;usd:number}[];limits:{meeting_usd:number;daily_usd:number;max_concurrent:number;max_minutes:number};meetings:{id:string;started:string;status:string;attendees:number;duration_ms:number;errors:number;estimated_usd:number;latency_total:number;latency_count:number}[]};
export function Admin() {
  const [stats,setStats]=useState<Stats|null>(null),[error,setError]=useState(''),[login,setLogin]=useState(false),[tab,setTab]=useState('overview');
  async function refresh(){try{setStats(await api('/api/admin'));setLogin(false);setError('');}catch(e){setError(String(e));setLogin(true);}}
  useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),10000);return()=>clearInterval(timer);},[]);
  if(login)return <Access role="admin" onReady={()=>void refresh()}/>;
  return <div className="app"><header><a className="brand" href="/">Audience / admin</a><button onClick={async()=>{await api('/api/auth/admin/logout',{});setLogin(true);}}>Sign out</button></header><main className="admin"><h1>Administration</h1><nav className="tabs" aria-label="Admin sections">{[["overview","Overview"],["settings","Models and providers"],["feedback","Feedback"]].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav><p role="alert">{error}</p>{stats&&<><section hidden={tab!=="overview"}><div className="stats"><article><h2>${stats.daily_by_stage.reduce((s,r)=>s+r.usd,0).toFixed(3)} / ${stats.limits.daily_usd.toFixed(2)}</h2><p>Estimated spend, {stats.today}, America/Chicago</p></article><article><h2>{stats.meetings.filter(m=>m.status==='active').length} / {stats.limits.max_concurrent}</h2><p>Active meetings</p></article><article><h2>${stats.limits.meeting_usd.toFixed(2)}</h2><p>Per meeting, up to {stats.limits.max_minutes} minutes</p></article></div><button onClick={async()=>{try{await api('/api/admin/admission',{paused:!stats.paused});await refresh();}catch(e){setError(String(e));}}}>{stats.paused?'Resume new meetings':'Pause new meetings'}</button><p>{stats.paused?'New meetings are paused. Existing meetings can finish.':'Accepting new meetings.'}</p><p className="hint">Conservative reservations plus reported usage where available, not a provider invoice. Cancelled requests retain their reservation. Stats persist. Transcripts are saved only with explicit feedback consent; no raw media is saved.</p><div className="stats">{stats.daily_by_stage.map(r=><p key={r.stage}>{r.stage}: ${r.usd.toFixed(4)}</p>)}</div><h2>Recent meetings</h2><div className="tableWrap"><table><thead><tr><th>Started (Chicago)</th><th>Session</th><th>Status</th><th>Attendees</th><th>Minutes</th><th>Estimated USD</th><th>Errors</th><th>First audio ms</th></tr></thead><tbody>{stats.meetings.map(m=><tr key={m.id}><td>{m.started}</td><td title={m.id}>{m.id.slice(0,8)}</td><td>{m.status}</td><td>{m.attendees}</td><td>{(m.duration_ms/60000).toFixed(1)}</td><td>{m.estimated_usd.toFixed(4)}</td><td>{m.errors}</td><td>{m.latency_count?Math.round(m.latency_total/m.latency_count):'No sample'}</td></tr>)}</tbody></table></div></section><Operations section={tab}/></>}</main></div>;
}
