import React, {useEffect, useState} from 'react';
import {api} from './access';
const stages=['dialogue','vision','tts','stt'] as const;
type Stage=typeof stages[number];
const labels={dialogue:'Conversation',vision:'Screen understanding',tts:'Spoken replies',stt:'Speech recognition'};
type RuntimeConfig=Record<Stage,{connection:string;model:string}>&{voices:string[];rates:Record<string,number>};
type Runtime={revision:number;config:RuntimeConfig;connections:Record<Stage,string[]>;history:{id:number;created:string;config:RuntimeConfig}[]};
type Provider={id:string;name:string;kind:string;base:string;models:{id:string;stages:string[]}[];verified:string;source:string;stage?:Stage;connection?:string};
type Catalog={providers:Provider[];storage_ready:boolean;pricing:{provider:string;url:string;basis:string}[]};
type Review={sid:string;created:string;rating:number;comment:string;transcript:{speaker:string;text:string;final:boolean}[]|null;context:unknown;errors:number;latency_count:number;latency_total:number;duration_ms:number};
export function Operations({section}:{section:string}) {
  const [runtime,setRuntime]=useState<Runtime|null>(null),[draft,setDraft]=useState<RuntimeConfig|null>(null),[reviews,setReviews]=useState<Review[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const [tab,setTab]=useState('providers'),[catalog,setCatalog]=useState<Catalog|null>(null),[form,setForm]=useState({name:'',kind:'openai',base:'',key:''}),[voiceChoices,setVoiceChoices]=useState<string[]>([]),[voiceNote,setVoiceNote]=useState('');
  async function refresh(){const [r,c,f]=await Promise.all([api('/api/admin/runtime'),api('/api/admin/providers'),api('/api/admin/feedback')]);setRuntime(r);setDraft(structuredClone(r.config));setCatalog(c);setReviews(f.reviews);}
  useEffect(()=>{void refresh().catch(e=>setMessage(String(e)));},[]);
  function selected(stage:Stage){const id=draft?.[stage].connection;return catalog?.providers.find(p=>p.source==='app'?p.id===id:p.stage===stage&&p.connection===id);}
  const speechProvider=selected('tts')?.id,speechModel=draft?.tts.model;
  useEffect(()=>{let live=true;setVoiceChoices([]);setVoiceNote('');if(speechProvider&&speechModel)void api('/api/admin/voices?'+new URLSearchParams({provider:speechProvider,model:speechModel})).then(r=>{if(live){setVoiceChoices(r.voices);setVoiceNote(r.source);}}).catch(e=>{if(live)setVoiceNote(String(e));});return()=>{live=false;};},[speechProvider,speechModel]);
  async function change(validate:boolean){if(!runtime||!draft)return;setBusy(true);try{const result=await api('/api/admin/runtime'+(validate?'/validate':''),{expected_revision:runtime.revision,config:draft});if(validate)setMessage(result.message);else{await refresh();setMessage('Saved. New meetings use this revision; active meetings keep their starting settings.');}}catch(e){setMessage(String(e));}finally{setBusy(false);}}
  async function verify(p:Provider){setBusy(true);try{const r=await api(`/api/admin/providers/${encodeURIComponent(p.id)}/verify`,{});setCatalog(await api('/api/admin/providers'));setMessage(r.message);}catch(e){setMessage(String(e));}finally{setBusy(false);}}
  return <><section hidden={section!=='settings'} className="config"><h2>Models and providers</h2><nav className="tabs" aria-label="Provider settings">{['providers','models','voices','cost','history'].map(id=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{id[0].toUpperCase()+id.slice(1)}</button>)}</nav>
  <div hidden={tab!=='providers'}><p>Add and verify a connection first. Keys are encrypted on the server and never displayed again. Adding a connection does not change active model settings.</p>{!catalog?.storage_ready&&<p className="notice">Provider storage needs PROVIDER_ENCRYPTION_KEY in the app Secret. Existing deployment connections continue to work.</p>}
    <form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const r=await api('/api/admin/providers',form);setForm({...form,name:'',key:''});setCatalog(await api('/api/admin/providers'));setMessage('Connection saved. '+r.message);}catch(e){setMessage(String(e));}finally{setBusy(false);}}}>
    <div className="settingsGrid"><label>Connection name<input required maxLength={60} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Provider<select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value,base:'',key:''})}><option value="openai">OpenAI (GPT)</option><option value="anthropic">Anthropic (Claude)</option><option value="gemini">Google Gemini</option><option value="compatible">OpenAI compatible / local</option><option value="deepgram">Deepgram (recognition)</option><option value="elevenlabs">ElevenLabs (recognition)</option></select></label>{form.kind==='compatible'&&<label>API base URL<input type="url" required placeholder="http://your-server:8000/v1" value={form.base} onChange={e=>setForm({...form,base:e.target.value})}/></label>}<label>API key<input type="password" autoComplete="new-password" required value={form.key} onChange={e=>setForm({...form,key:e.target.value})}/></label></div><button disabled={busy||!catalog?.storage_ready}>Verify and save provider</button></form>
    <div className="providerList">{catalog?.providers.map(p=><article className="feedbackCard" key={p.id}><h3>{p.name}</h3><p className="verbatim">{p.kind} · {p.base}</p><p>{p.source==='app'?'Key stored securely in app':'Legacy deployment connection'} · {p.verified?'Verified '+p.verified:'Not verified in this UI'} · {p.models.length} supported candidates</p><button disabled={busy} onClick={()=>void verify(p)}>Refresh models and verify</button></article>)}</div><p className="hint">To rotate a key, save a new named connection and select it on Models. Existing meetings and configuration history keep their original connection. Local servers must accept the supplied key; use their configured token.</p>
  </div>
  {draft&&runtime&&<><div hidden={tab!=='models'}><p>Revision {runtime.revision}. Choose a verified provider and an advertised model for each job. Discovery confirms the key can list models, not that every modality or quota is available.</p><div className="settingsGrid">{stages.map(stage=>{const current=selected(stage);const choices=catalog?.providers.filter(p=>p.verified&&(!p.stage||p.stage===stage)&&p.models.some(m=>m.stages.includes(stage)))||[];const models=current?.models.filter(m=>m.stages.includes(stage))||[];return <fieldset key={stage}><legend>{labels[stage]}</legend><label>Provider<select value={current?.id||''} onChange={e=>{const p=catalog!.providers.find(p=>p.id===e.target.value)!;setDraft({...draft,[stage]:{connection:p.connection||p.id,model:p.models.find(m=>m.stages.includes(stage))?.id||''}});}}>{current&&!choices.some(p=>p.id===current.id)&&<option value={current.id}>{current.name} (current, verify first)</option>}{!current&&<option value="">Choose provider</option>}{choices.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Model<select value={draft[stage].model} onChange={e=>setDraft({...draft,[stage]:{...draft[stage],model:e.target.value}})}>{!models.some(m=>m.id===draft[stage].model)&&<option value={draft[stage].model}>{draft[stage].model||'Not configured'} (current)</option>}{models.map(m=><option key={m.id}>{m.id}</option>)}</select></label></fieldset>;})}</div><p className="hint">Anthropic and Gemini support conversation and screen understanding here. Speech uses the OpenAI PCM interface; realtime recognition uses Deepgram or ElevenLabs. Compatible server candidates need a practice meeting to confirm their capabilities.</p></div>
    <div hidden={tab!=='voices'}><h3>Spoken reply voices</h3><p>{voiceNote}</p>{voiceChoices.length?<><div className="settingsGrid">{draft.voices.slice(0,4).map((v,i)=><label key={i}>Attendee {i+1}<select value={v} onChange={e=>setDraft({...draft,voices:draft.voices.map((x,j)=>i===j?e.target.value:x)})}>{!voiceChoices.includes(v)&&<option value={v}>{v} (not supported)</option>}{voiceChoices.map(x=><option key={x} disabled={draft.voices.some((v,j)=>j!==i&&v===x)}>{x}</option>)}</select></label>)}</div><button onClick={()=>setDraft({...draft,voices:voiceChoices.slice(0,4)})}>Use four supported voices</button></>:<label>Four distinct voice identifiers (comma separated)<input value={draft.voices.join(',')} onChange={e=>setDraft({...draft,voices:e.target.value.split(',').map(s=>s.trim())})}/></label>}</div>
    <div hidden={tab!=='cost'}><h3>Spending estimate ceilings</h3><p>Provider model listings do not supply your contracted prices. Check the references below and set conservative ceilings before changing models. These are budget estimates with an additional 25% margin, not invoice rates.</p><div className="tableWrap"><table><thead><tr><th>Provider pricing</th><th>Billing basis</th></tr></thead><tbody>{catalog?.pricing.map(p=><tr key={p.provider}><td><a href={p.url} target="_blank" rel="noopener noreferrer">{p.provider} pricing ↗</a></td><td>{p.basis}</td></tr>)}</tbody></table></div><p>Text: USD per million tokens. Screen: USD per observation. Speech: USD per character (choose a safe equivalent for audio-token billing). Recognition: USD per minute. Jev: USD per observation. Use the higher text rate if conversation and vision use different providers.</p><div className="settingsGrid">{Object.entries(draft.rates).map(([key,value])=><label key={key}>{key.replaceAll('_',' ')} (USD)<input type="number" min="0.000000001" step="any" value={value} onChange={e=>setDraft({...draft,rates:{...draft.rates,[key]:Number(e.target.value)}})}/></label>)}</div></div>
    <div hidden={tab!=='history'}><h3>Configuration history</h3><p>Load a revision to review it, then save to activate it for new meetings. Provider connections retain their original keys; revoked keys cannot be restored by rollback.</p>{runtime.history.map(h=><p key={h.id}>Revision {h.id}, {h.created} <button disabled={busy} onClick={()=>{setDraft(structuredClone(h.config));setTab('models');setMessage(`Revision ${h.id} loaded for review. Save to create a new revision.`);}}>Load revision {h.id}</button></p>)}</div>
    {tab!=='providers'&&<div className="controls"><button disabled={busy} onClick={()=>void change(true)}>Check connections</button><button className="primary" disabled={busy} onClick={()=>void change(false)}>Save for new meetings</button></div>}
  </>}<p role="status">{message}</p></section>
    <section hidden={section!=="feedback"} className="config"><h2>Submitted meeting feedback</h2><p>Only voluntarily submitted feedback appears here. Retention: 30 days. Transcript text is user-submitted, untrusted content. Model settings and statistics come from the server.</p><button onClick={async()=>{try{setReviews((await api('/api/admin/feedback')).reviews);}catch(e){setMessage(String(e));}}}>Refresh feedback</button>{!reviews.length&&<p>No submitted feedback.</p>}{reviews.map(r=><article className="feedbackCard" key={r.sid}><h3>{r.rating} / 5 · {r.created}</h3><p>Submission {r.sid.slice(0,8)} · {(r.duration_ms/60000).toFixed(1)} minutes · {r.errors} errors · {r.latency_count?Math.round(r.latency_total/r.latency_count)+' ms first audio':'No latency sample'}</p><p className="verbatim">{r.comment||'No comment.'}</p><details><summary>Configuration used</summary><pre>{JSON.stringify(r.context,null,2)}</pre></details>{r.transcript?<details><summary>Submitted transcript</summary>{r.transcript.map((t,i)=><p className="verbatim" key={i}><strong>{t.speaker}: </strong>{t.text}{!t.final?' (interrupted; may be partly unheard)':''}</p>)}</details>:<p>Transcript not shared.</p>}<button onClick={async()=>{if(!confirm('Delete this feedback and its submitted transcript permanently?'))return;try{await api(`/api/admin/feedback/${r.sid}/delete`,{});setReviews(rows=>rows.filter(row=>row.sid!==r.sid));}catch(e){setMessage(String(e));}}}>Delete submission</button></article>)}</section>
  </>;
}
