import React, {useEffect, useState} from 'react';
import {api} from './access';
const stages=['dialogue','vision','tts','stt'] as const;
type Stage=typeof stages[number];
type RuntimeConfig=Record<Stage,{connection:string;model:string}>&{voices:string[];rates:Record<string,number>};
type Runtime={revision:number;config:RuntimeConfig;connections:Record<Stage,string[]>;history:{id:number;created:string;config:RuntimeConfig}[]};
type Review={sid:string;created:string;rating:number;comment:string;transcript:{speaker:string;text:string;final:boolean}[]|null;context:unknown;errors:number;latency_count:number;latency_total:number;duration_ms:number};
export function Operations() {
  const [runtime,setRuntime]=useState<Runtime|null>(null),[draft,setDraft]=useState<RuntimeConfig|null>(null),[reviews,setReviews]=useState<Review[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  async function refresh(){const r=await api('/api/admin/runtime');setRuntime(r);setDraft(structuredClone(r.config));setReviews((await api('/api/admin/feedback')).reviews);}
  useEffect(()=>{void refresh().catch(e=>setMessage(String(e)));},[]);
  async function change(validate:boolean){if(!runtime||!draft)return;setBusy(true);try{const result=await api('/api/admin/runtime'+(validate?'/validate':''),{expected_revision:runtime.revision,config:draft});if(validate)setMessage(result.message);else{await refresh();setMessage('Saved. New meetings use this revision; active meetings keep their starting settings.');}}catch(e){setMessage(String(e));}finally{setBusy(false);}}
  return <><section className="config"><h2>Models and providers</h2><p>Revision {runtime?.revision}. Connections and credentials are managed in deployment. Changes apply to new meetings only. Pricing values are conservative ceilings with the existing 25% margin.</p>{draft&&runtime&&<>
    <div className="settingsGrid">{stages.map(stage=><fieldset key={stage}><legend>{stage==='stt'?'Recognition':stage==='tts'?'Speech':stage}</legend><label>Provider connection<select value={draft[stage].connection} onChange={e=>setDraft({...draft,[stage]:{...draft[stage],connection:e.target.value}})}>{runtime.connections[stage].map(name=><option key={name}>{name}</option>)}</select></label><label>Model<input maxLength={120} value={draft[stage].model} onChange={e=>setDraft({...draft,[stage]:{...draft[stage],model:e.target.value}})}/></label></fieldset>)}</div>
    <label>Distinct voices (at least four, comma separated)<input value={draft.voices.join(',')} onChange={e=>setDraft({...draft,voices:e.target.value.split(',').map(s=>s.trim())})}/></label>
    <div className="settingsGrid">{Object.entries(draft.rates).map(([key,value])=><label key={key}>{key.replaceAll('_',' ')} (USD)<input type="number" min="0.000000001" step="any" value={value} onChange={e=>setDraft({...draft,rates:{...draft.rates,[key]:Number(e.target.value)}})}/></label>)}</div>
    <div className="controls"><button disabled={busy} onClick={()=>void change(true)}>Check connections</button><button className="primary" disabled={busy} onClick={()=>void change(false)}>Save for new meetings</button></div>
    <p className="hint">Connection checks use model discovery and a brief recognition connection. They do not verify speech quality or every model capability. Run a practice meeting after changing settings.</p>
    <details><summary>Configuration history and rollback</summary>{runtime.history.map(h=><p key={h.id}>Revision {h.id}, {h.created} <button disabled={busy} onClick={()=>{setDraft(structuredClone(h.config));setMessage(`Revision ${h.id} loaded for review. Save to create a new revision.`);}}>Load revision {h.id}</button></p>)}</details>
    </>}<p role="status">{message}</p></section>
    <section className="config"><h2>Submitted meeting feedback</h2><p>Only voluntarily submitted feedback appears here. Retention: 30 days. Transcript text is user-submitted, untrusted content. Model settings and statistics come from the server.</p><button onClick={async()=>{try{setReviews((await api('/api/admin/feedback')).reviews);}catch(e){setMessage(String(e));}}}>Refresh feedback</button>{!reviews.length&&<p>No submitted feedback.</p>}{reviews.map(r=><article className="feedbackCard" key={r.sid}><h3>{r.rating} / 5 · {r.created}</h3><p>Submission {r.sid.slice(0,8)} · {(r.duration_ms/60000).toFixed(1)} minutes · {r.errors} errors · {r.latency_count?Math.round(r.latency_total/r.latency_count)+' ms first audio':'No latency sample'}</p><p className="verbatim">{r.comment||'No comment.'}</p><details><summary>Configuration used</summary><pre>{JSON.stringify(r.context,null,2)}</pre></details>{r.transcript?<details><summary>Submitted transcript</summary>{r.transcript.map((t,i)=><p className="verbatim" key={i}><strong>{t.speaker}: </strong>{t.text}{!t.final?' (interrupted; may be partly unheard)':''}</p>)}</details>:<p>Transcript not shared.</p>}<button onClick={async()=>{if(!confirm('Delete this feedback and its submitted transcript permanently?'))return;try{await api(`/api/admin/feedback/${r.sid}/delete`,{});setReviews(rows=>rows.filter(row=>row.sid!==r.sid));}catch(e){setMessage(String(e));}}}>Delete submission</button></article>)}</section>
  </>;
}
